# Generated by Django 5.0.4 on 2024-04-29 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_accesskey_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 12, 35, 29, 382641)),
        ),
    ]
