# Generated by Django 5.0.4 on 2024-05-07 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_revoked_accesskey_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 16, 41, 2, 320705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
